"""initial migration

Revision ID: 801e6dfc85e9
Revises: 
Create Date: 2017-08-15 03:49:08.280839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801e6dfc85e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_temperature', table_name='weather')
    op.create_unique_constraint(None, 'weather', ['temperature'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather', type_='unique')
    op.create_index('ix_weather_temperature', 'weather', ['temperature'], unique=1)
    # ### end Alembic commands ###
